
version: '3.8'

services:
  uberapp:
    build: .
    container_name: uber-trip-simulator
    ports:
      - "5004:5004"
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - uber_network

networks:
  uber_network:
    driver: bridge
